export const ParalelicRoutes:{[key:string]:any} = {
    'authentication': 'CHECK_IN_APP',
    'checkin' : 'CHECK_IN',
    'login':'LOGIN',
    'singup':'SIGN_UP',
    'guest-nickname':'GUEST_USERNAME',
    'form' : 'CREATE_FORMS',
    'add_question' : 'ADD_QUESTION',
    'form_name':'FORM_NAME',
    'review_form':'REVIEW_FORM',
    'game':'PLAYABLE_APP',
    'question_step':'QUESTION_STEP',
    'question_await_step':'QUESTION_AWAIT_STEP',
    'result':'RESULT',
    'waiting_room':'WAITING_ROOM',
    'chat_room':'CHATROOM',
    'final': 'FINAL_STEP',
    'master-room': 'MASTER_ROOM',
};

/***
 * CHECK_IN_APP= 'authentication',
    CHECK_IN = 'checkin',
    LOGIN='login',
    SIGN_UP='singup',
    GUEST_USERNAME='guest-nickname',
    CREATE_FORMS = 'form',
    ADD_QUESTION = 'add_question',
    FORM_NAME='form_name',
    REVIEW_FORM='review_form',
    PLAYABLE_APP='game',
    QUESTION_STEP='question_step',
    QUESTION_AWAIT_STEP='question_await_step',
    RESULT='result',
    WAITING_ROOM='waiting_room',
    CHATROOM='chat_room',
    FINAL_STEP= 'final'
 */