export enum RouterNavigate{
    CHECK_IN_APP= 'authentication',
    CHECK_IN = 'checkin',
    LOGIN='login',
    SIGN_UP='singup',
    GUEST_USERNAME='guest-nickname',
    CREATE_FORMS = 'form',
    ADD_QUESTION = 'add_question',
    FORM_NAME='form_name',
    REVIEW_FORM='review_form',
    PLAYABLE_APP='game',
    QUESTION_STEP='question_step',
    QUESTION_AWAIT_STEP='question_await_step',
    RESULT='result',
    WAITING_ROOM='waiting_room',
    CHATROOM='chat_room',
    FINAL_STEP= 'final',
    MASTER_ROOM= 'master-room',
}